### PR TITLE
Improve Error handling and some misc items

### PR DESCRIPTION
**Pull request by iva2k**
# Description
* Add better error handling to Session/Channel/arp
* Ensure channel.idx is unique in Session
* Add fullShuffle option to shuffle() util
* Fix clip.test.ts sporadic fails when shuffle() keeps tested notes in place - by shuffle(fullShuffle = true)

# CheckLists
_Complete the items prior to reviews_
- [ ] Add Labels
- [x] Unit Testing

# References
- [Creating a pull request template for your repository](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)

### CODE REVIEW

**Comment by walmik** [comment]
Looks good @iva2k Can you please bump minor version, i ll merge and publish this. (minor coz unique idx and full shuffle are kinda like small features than fixes)

**Comment by walmik** [comment]
Also since this PR is fixing some issues, would it be a good idea to change `import { clip } from './clip';` to `import { clip } from './browser-clip';` in channel.ts?

**Comment by iva2k** [comment]
ok, done!

**Comment by walmik** [comment]
👍  thank you @iva2k

**Review by walmik — APPROVED** [review]

**Pull request merged**
