### PR TITLE
browser mode uses the correct tone length.

### PR DESCRIPTION
**Pull request by mikesmit**
Previously every tone was the duration length for the clip even if the note was subdivided. This change pulls out the computation of note length into common code which is then used by the browserClip and by the normal clip when generating midi.

### CODE REVIEW

**Comment by walmik** [comment]
Hi @mikesmit Thank you for your contribution! I m sorry for the delay in replying here (I was a bit held up in stuff). I ll play around with this change locally. In the mean time can you please add tests that support this change?

**Comment by mikesmit** [comment]
Sure. What do you want to see specifically? This change should be transparent to clip (and be exercised by those tests). for browserclip I didn't see existing tests to add to.

**Comment by walmik** [comment]
Hello @mikesmit I cloned your branch locally and tried out a few things while doing the same from my branch. I generated few MIDI files from both the branches (with and without subdivisions) and imported them into Ableton Live. I also consoled out their lengths. I couldnt see any difference in the MIDI files or the clips generated.

Could you please explain to me what issue is this change fixing? Would you kindly provide me with a script/scenario that I can run locally in both the branches and see the issue for my self. Later we can use those scenarios to have some tests. For now however, I m keen on clearly understanding the issue we are fixing via these changes.

**Comment by mikesmit** [comment]
The MIDI is identical. This fixes a bug in the tonejs webclip implementation. If you create a clip where the length of a note is longer than the subdiv like this:
```
const c = clip({
	notes: 'c4',
	pattern: 'x___x___'
}).play
```

The c4 will actually only play for one div instead of 4.
This is because the existing tonejs implementation just uses the div length for the length of every note instead of computing the length from the pattern.
This change is pulling out code for computing the length from the MIDI and then reusing it for both the MIDI generation and the tonejs implementation.

**Comment by mikesmit** [comment]
So like here: https://github.com/scribbletune/scribbletune/blob/master/src/browserClip.js#L29 . Instead of having a per-note value for the length of the note it's using a clip level value (i.e. params.dur, etc.)

**Comment by mikesmit** [comment]
This change passes a set of durations along with the notes and then uses that first: https://github.com/scribbletune/scribbletune/pull/77/commits/07ea00ba2552d0f261faaad45b1bb18a8cdf7cf3#diff-d5d4b703384ca13d26da418b88fd2510R29

**Comment by walmik** [comment]
I ve fixed the linter @mikesmit You may get a conflict in src/clip.js but it s a very simple resolve. Once you resolve it, you can run `npm run lint` and see the minor lint issues.

**Comment by walmik** [comment]
@mikesmit Hi Mike, just a gentle reminder for the minor change required here.. I m keen on merging this for the upcoming 2.0 major version release.

**Comment by mikesmit** [comment]
Hey! I'm sorry. Life has gotten very busy, but I will try to get to this.

**Comment by walmik** [comment]
Hi @mikesmit closing this PR based on #104 in which @qchenevier used some inspiration from this PR of yours (in other words your contribution to Scribbletune is still very much a reality). Hope you re ok with this being closed.

**Comment by mikesmit** [comment]
Hey! That's awesome:) I am otherwise a massive failure as a contributor so
that's pretty exciting.

**Pull request closed without merging**
