### PR TITLE
In browser mode, infer the correct duration of the note from the pattern

### PR DESCRIPTION
**Pull request by qchenevier**
Hi,

I propose a minor change to be able ~to give the duration parameter as an array or a string of values~ to infer the duration of the note from the pattern (for a melody pattern). You can also force all the notes to have the same duration, if you specify it (for a beat pattern).

### Before
```javascript
scribble
  .clip({
    synth: 'Synth',
    pattern:  'x[xx][x[xx]]x_x',
    notes: 'C4 D4 C4 D#4 C4 D4 C4 Bb3',
    // no "dur" specified: only one duration for all the notes of the clip, default value: "4n"
  })
  .start();
```

### After 
Melody mode
```javascript
scribble
  .clip({
    synth: 'Synth',
    pattern: 'x[xx][x[xx]]x_x',
    notes: 'C4 D4 C4 D#4 C4 D4 C4 Bb3',
    // no "dur specified": duration dynamically inferred from the the pattern
    // here: ["4n", "8n", "8n", "8n", "16n", "16n", "2n", "4n"]
  })
  .start();
```

Beat mode
```javascript
scribble
  .clip({
    synth: 'Synth',
    pattern: 'x[xx][x[xx]]x_x',
    notes: 'C4 D4 C4 D#4 C4 D4 C4 Bb3',
    dur: '16n' // only one duration for all notes. you can only specify a single duration.
  })
  .start();
```

> I'm pretty noob in js and even more in ts, so be nice. 😊

### CODE REVIEW

**Comment by walmik** [comment]
Hello @qchenevier ! Thank you for taking the time to go over an implementation for this. It is certainly a desired feature, however I was hoping it was approached a bit differently. The duration  should ideally be adjusted dynamically as opposed to providing them individually. The pattern language of `x`, `-`, `_`, `[`, `]` should be the one driving the duration.

You re right about the issue.. having it the same for each note is not optimal. In fact we have a open PR that attempted this issue in a dynamic sorta way.. you can check out PR #77 from @mikesmit who had started this change some time ago.. but neither of us got to it. If you want you can take a look at it and see if we can make this duration thing dynamic as part of your PR by taking some refs from #77 

For e.g. if the default dur is 4n... for each incoming x it can continue to be 4n but as soon as it s split.. eg `[xx]` then the dur dynamically becomes 8n for the duration of the split.. and comes back to 4n after the subdivision is complete for the subsequent x. Hope it makes sense!

**Comment by qchenevier** [comment]
> The pattern language of `x`, `-`, `_`, `[`, `]` should be the one driving the duration.

Yeah, I originally thought the same when I looked at the discussion in #77 . But when I did some tests with beat patterns (e.g: using [MembraneSynth](https://tonejs.github.io/docs/MembraneSynth)), I realized you don't want the beat sound to be shorter when you are subdividing (e.g: `"xxx[x-xx]"` --> _tum tum tum tum tutu-tum_).

So I hacked something simple which would let met specify the duration I needed for every case (melody & beats). I understand that it's not satisfactory as it completely ignores the notation of the pattern langage.

I guess that a nice design would be:
- if `dur` is **undefined**, the duration is dynamically determined by the pattern: `x`is `4n`, [x] is `8n`, `x_` is `2n` and so on. (melody use-case)
- if `dur` is **defined**, it should be a single value & the duration is the same for all notes (beats use-case)

What do you think ?

I fairly new to js/ts but I guess I can manage to do a PR for this simple design.

**Comment by walmik** [comment]
Yes makes sense. Another usecase is if a pattern is playing the same note then you d want the pattern to be governed by the pattern language but if it s multiple notes, then you may want to define a specific length via `dur`.. 
dur

**Comment by qchenevier** [comment]
So I took inspiration from #77 and did a little bit of refactoring. What do you think @walmik ?

Maybe add some tests ?

**Comment by walmik** [comment]
This looks awesome @qchenevier ! We currently dont have tests for browserClip (rest of the files have tests) hence I m gonna clone your branch locally and try out few things manually (you re certainly free to add tests ofc!) But good stuff buddy.. lets get this in soon :)

**Comment by walmik** [comment]
@qchenevier I cloned your branch and tried out the changes.. it all looks good 👍 Just want to confirm that the dur value continues to be a single string e.g, `4n` or `16n` and not a string of values such as `4n 8n 4n 16n` as suggested in the PR description (if so can you please update the description)

In my local tests I tried this existing non browser features as well as the following clip with and without the changes introduced in this PR and I was satisfied to see that the PolySynth was not trailing off!

```
clip({
  synth: 'PolySynth',
  notes: 'C2',
  pattern: '[[xx][xx]]',
}).start();
```

**Comment by qchenevier** [comment]
First comment updated according to the design of the code.

**Comment by walmik** [comment]
Thank you @qchenevier i m really excited for this new improvement. I ll bump the minor version along with some more housekeeping and publish soon.. Once published it will be on CDNjs in 2-3 days... Will keep you posted! One more time -> Thank you for this long awaited change.. i m sure @mikesmit is gonna be happy bout it too :)

**Pull request merged**
