### PR TITLE
Add an optional bpm argument to the midi method.

### PR DESCRIPTION
**Pull request by Kylir**
Hello there,

In my Node project I would like to be able to set the tempo of a midi file. I believe this is issue #9 .

This pull request allows a user to pass a third argument to the `midi` method to set the tempo.
This is using the `setTempo` function in `jsmidgen`.

I added the code, one example and one test - I didn't know where to change the documentation.
I'm not usually using TypeScript, so please double check that my type definitions are correct.

Also, I appreciate the test I added is not optimal... I searched for a way to parse the generated midi files and compare the tempos. The best I came up with is to compare two bytes.

### CODE REVIEW

**Comment by Kylir** [comment]
I had a little moment of panic when I realized I might have pushed some midi files in the pull request!
But no, the `.gitignore` file file saved me! Nice job who added the exclusion of the `.mid`.

**Comment by walmik** [comment]
Hello @Kylir Apologies for the delay in responding here [just swamped at work!]

Changes look good to me. May I request @mickmister or @qchenevier to take a look as well?

**Comment by qchenevier** [comment]
This is nice ! And with tests ! Changes look good to me also.

@Kylir Yeah, the test feels like a retro-engineering made from the output you got. Testing binary output is hard. What do you think of parsing the midi output with https://github.com/Tonejs/Midi and do the tests on the properties we get from the parser ? It would allow to write tests which would be more human-readable. But this an additional dev dependency...

@walmik what do you think ?

**Comment by walmik** [comment]
That s a fantastic idea @qchenevier It can even get our browser tests from its almost non existent state to a very admirable level!

Thank you @Kylir for your contribution. We do have a [jekyll based documentation repo](https://github.com/scribbletune/scribbletune.com). No one s created a PR there as yet as it may need wire up some amount of Ruby [on a Mac it s already wired up but not sure if the same is done on Windows and Linux] I ll merge this PR now and update the docs over the weekend. Thank you @qchenevier and @mickmister for the review & approval 👍

**Comment by Kylir** [comment]
Sorry! Just catching up...

Thanks for reviewing, accepting and merging!

@qchenevier about the tests, very good idea! The parser would help. I _may_ have a look at some point.

**Pull request merged**
